spring.application.name=HolaSpring
spring.main.banner-mode=off
server.port=8081
#logging.level.root=INFO
#logging.level.avilawebservice=DEBUG
logging.pattern.dateformat=hh:mm
spring.thymeleaf.cache=false
index.saludo=Adios desde application.properties