form.usuario:Usuario
form.password:Password
form.boton:Enviar
form.titulo:Login


bienvenido.titulo:Bienvenido
bienvenido.mensaje:Usuario Correcto
bienvenido.regresar:Regresar

usuario.valido:El Usuario es valido
val.usuario:El campo de Usuario es requerido
usuario.invalido:El Usuario no es valido
val.password:El campo de password es requerido
val.pass.min.lenght:El password tiene que tener al menos 3 caracteres