package avilawebservice.servicio;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-21T19:09:35.914-06:00
 * Generated source version: 4.1.1
 *
 */
@WebService(targetNamespace = "http://servicio.avilawebservice/", name = "PersonaServiceWs")
@XmlSeeAlso({ObjectFactory.class})
public interface PersonaServiceWs {

    @WebMethod
    @Action(input = "http://servicio.avilawebservice/PersonaServiceWs/listarPersonasRequest", output = "http://servicio.avilawebservice/PersonaServiceWs/listarPersonasResponse")
    @RequestWrapper(localName = "listarPersonas", targetNamespace = "http://servicio.avilawebservice/", className = "avilawebservice.servicio.ListarPersonas")
    @ResponseWrapper(localName = "listarPersonasResponse", targetNamespace = "http://servicio.avilawebservice/", className = "avilawebservice.servicio.ListarPersonasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<avilawebservice.servicio.Persona> listarPersonas();
}
