package avilawebservice.servicio;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-21T19:09:35.973-06:00
 * Generated source version: 4.1.1
 *
 */
@WebServiceClient(name = "PersonaServiceImplService",
                  wsdlLocation = "http://localhost:8080/PersonaServiceImplService/PersonaServiceImpl?wsdl",
                  targetNamespace = "http://servicio.avilawebservice/")
public class PersonaServiceImplService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://servicio.avilawebservice/", "PersonaServiceImplService");
    public static final QName PersonaServiceImplPort = new QName("http://servicio.avilawebservice/", "PersonaServiceImplPort");
    static {
        URL url = null;
        try {
            url = URI.create("http://localhost:8080/PersonaServiceImplService/PersonaServiceImpl?wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PersonaServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/PersonaServiceImplService/PersonaServiceImpl?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PersonaServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PersonaServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonaServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PersonaServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PersonaServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PersonaServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PersonaServiceWs
     */
    @WebEndpoint(name = "PersonaServiceImplPort")
    public PersonaServiceWs getPersonaServiceImplPort() {
        return super.getPort(PersonaServiceImplPort, PersonaServiceWs.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonaServiceWs
     */
    @WebEndpoint(name = "PersonaServiceImplPort")
    public PersonaServiceWs getPersonaServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PersonaServiceImplPort, PersonaServiceWs.class, features);
    }

}
