spring.application.name=recursoHumanos

# ---- Configuración de la base de datos MySQL ----
spring.datasource.url=jdbc:mysql://localhost:3307/recurso_humanos_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=curso123

# ---- Driver de MySQL ----
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Connection pool logs in console(configuration patron de log)
logging.level.root=INFO
logging.pattern.console=[%thread] %-5level: %logger - %msg%n

# Spring Boot Banner:console (default) log or off
spring.main.banner-mode=off

# Configuración del puerto del servidor (opcional, por defecto es 8080)
#server.port=8081