
package clientews.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ServicioSumarImplService", targetNamespace = "http://beans.avilaswebservice/", wsdlLocation = "http://localhost:8080/ServicioSumarImplService/ServicioSumarImpl?wsdl")
public class ServicioSumarImplService
    extends Service
{

    private static final URL SERVICIOSUMARIMPLSERVICE_WSDL_LOCATION;
    private static final WebServiceException SERVICIOSUMARIMPLSERVICE_EXCEPTION;
    private static final QName SERVICIOSUMARIMPLSERVICE_QNAME = new QName("http://beans.avilaswebservice/", "ServicioSumarImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ServicioSumarImplService/ServicioSumarImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOSUMARIMPLSERVICE_WSDL_LOCATION = url;
        SERVICIOSUMARIMPLSERVICE_EXCEPTION = e;
    }

    public ServicioSumarImplService() {
        super(__getWsdlLocation(), SERVICIOSUMARIMPLSERVICE_QNAME);
    }

    public ServicioSumarImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOSUMARIMPLSERVICE_QNAME, features);
    }

    public ServicioSumarImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOSUMARIMPLSERVICE_QNAME);
    }

    public ServicioSumarImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOSUMARIMPLSERVICE_QNAME, features);
    }

    public ServicioSumarImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioSumarImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioSumarWS
     */
    @WebEndpoint(name = "ServicioSumarImplPort")
    public ServicioSumarWS getServicioSumarImplPort() {
        return super.getPort(new QName("http://beans.avilaswebservice/", "ServicioSumarImplPort"), ServicioSumarWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioSumarWS
     */
    @WebEndpoint(name = "ServicioSumarImplPort")
    public ServicioSumarWS getServicioSumarImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://beans.avilaswebservice/", "ServicioSumarImplPort"), ServicioSumarWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOSUMARIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICIOSUMARIMPLSERVICE_EXCEPTION;
        }
        return SERVICIOSUMARIMPLSERVICE_WSDL_LOCATION;
    }

}
